server:
  port: 8080

logging:
  level:
    com.julianw03.rcls: DEBUG

custom:
  configurations:
    riotclient-service:
      connection-strategy:
        strategy: process_takeover
    publishing:
      publishing-format: raw_json