server:
  port: 8080

logging:
  level:
    com.julianw03.rcls.service.base.riotclient.RiotClientServiceImpl: DEBUG
    com.julianw03.rcls.service.base.process.ProcessService: DEBUG

custom:
  configurations:
    riotclient-service:
      connection-strategy:
        strategy: process_takeover